---
name: Lint

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: "**/*.md"
